[tool.black]
extend-exclude = '(.*\/migrations/*|\.env)'
icons = true
line-length = 79

[tool.isort]
known_local_folder = ['../../../App/']
skip_glob = ['**/migrations/*', '**/.env/*']
lines_after_imports = 2
force_single_line = true
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3
known_third_party = ['django', 'pytest']
