name: Code format checker CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ğŸ“ Check lint
      run: make check-lint
    - name: ğŸ”¢ Check imports order
      run: make check-sort-imports
    - name: ğŸ³ Setup container
      run: make upd
    - name: â³ Wait for the environment to get up
      run: make wait-db
    - name: âœ… Test
      run: make test
