name: Code format checker CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ğŸ” Install linter
      run: pip3 install oitnb==0.2.2
    - name: ğŸ“ Check lint
      run: make check-lint-local
    - name: ğŸ“– Install sorter
      run: pip3 install isort==5.10.1
    - name: ğŸ”¢ Check imports order
      run: make check-sort-imports-local
    - name: ğŸ³ Setup container
      run: make upd
    - name: â³ Wait for the environment to get up
      run: make wait-db
    - name: âœ… Test
      run: make test
