name: Code quality checker CI

on:
  push:
    branches:    
      - 'master'
      - 'staging'
      - 'dev' 
      - 'create-github-actions'
  pull_request:
    branches:    
      - 'master'
      - 'staging'
      - 'dev'

jobs:
  Code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ğŸ“ Check lint
      run: pip3 install oitnb==0.2.2 && make check-lint-local
    - name: ğŸ† Check imports order
      run: pip3 install isort==5.10.1 && make check-sort-imports-local
    - name: ğŸ³ Setup container
      run: make upd
    - name: â³ Wait for the environment to get up
      run: make wait-db
    - name: âœ… Test
      run: make test
    - name: ğŸ‰ Congratulations
      run: echo "Everything is okay! ğŸ‰"
