name: Deploy code on environments

on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'dev'
      - 'create-github-actions'
  pull_request:
    branches:
      - 'master'
      - 'staging'
      - 'dev'

jobs:
  Code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: ğŸš Deploy on PRE
    # - name: ğŸ›« Deploy on Staging
    # - name: ğŸš€ Deploy on Production
    - name: ğŸ‰ Congratulations
      run: echo "Everything is okay! ğŸ‰"
